docker-deploy/web-app/SuperRide/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('account/', include('account.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('ride/', include('ride.urls')),
]

docker-deploy/web-app/ride/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('request/', views.make_request, name='make-ride-request'),
    path('my-rides/<str:mode>', views.display_my_rides, name='show-my-rides'),
    path('edit-request/<int:ride_id>', views.edit_request, name='edit-ride'),
    path('detail/<int:ride_id>/<str:mode>/<int:share_ride_id>/<str:back_url>', views.view_ride, name='view-ride'),
    path('open-for-driver/', views.open_rides_drive, name='open-rides-drive'),
    path('open-for-sharer/', views.open_rides_share, name='open-rides-share'),
    path('drive-ride/<int:ride_id>', views.drive_ride, name='drive-ride'),
    path('share-ride/<int:ride_id>/<int:share_ride_id>', views.share_ride, name='share-ride'),
    path('complete-ride/<int:ride_id>', views.complete_ride, name='complete-ride'),
    path('quit-ride/<int:ride_id>', views.quit_ride, name='quit-ride'),
]

docker-deploy/web-app/ride/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone

CAR_TYPES = [
    ('NONE', 'Unknown'),
    ('SEDAN', 'Sedan'),
    ('COUPE', 'Coupé'),
    ('CONV','Convertible'),
    ('SUV', 'SUV'),
    ('VAN', 'Van'),
    ('WAGON', 'Wagon'),
    ('SPORT', 'Sports car'),
    ('OTHER', 'Other'),
]

def validate_not_earlier_than_now(value):
    if value < timezone.now():
        raise ValidationError("Date must not be earlier than current time")

class Ride(models.Model):
    owner = models.ForeignKey('account.MyUser', on_delete=models.CASCADE, blank=True, null=True, related_name='owner_rides')
    driver = models.ForeignKey('account.MyUser', on_delete=models.CASCADE, blank=True, null=True, related_name='driver_rides')
    destination = models.CharField(max_length=100, blank=True, null=True)
    arrival_time = models.DateTimeField(validators=[validate_not_earlier_than_now], blank=True, null=True)
    number_of_passengers = models.IntegerField(blank=True, null=True)
    number_of_passengers_sum = models.IntegerField(blank=True, null=True)
    shared = models.BooleanField(default=False)
    STATUS_CHOICES = [
        ('OPEN', 'Open'),
        ('CONFIRMED', 'Confirmed'),
        ('COMPLETE', 'Complete'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='OPEN')
    vehicle_type = models.CharField(max_length=5, choices=CAR_TYPES, default='NONE')
    special_request = models.CharField(max_length=200, blank=True, null=True)

class ShareRide(models.Model):
    destination = models.CharField(max_length=100, blank=True, null=True)
    earliest_time = models.DateTimeField(validators=[validate_not_earlier_than_now], blank=True, null=True)
    latest_time = models.DateTimeField(validators=[validate_not_earlier_than_now], blank=True, null=True)
    number_of_passengers = models.IntegerField(blank=True, null=True)
    ride = models.ForeignKey(Ride, on_delete=models.CASCADE, blank=True, null=True)
    owner = models.ForeignKey('account.MyUser', on_delete=models.CASCADE, blank=True, null=True, related_name='share_rides_detail')

class Vehicle(models.Model):
    plate_num = models.CharField(max_length=10, verbose_name='Plate number',blank=True, null=True)
    type = models.CharField(max_length=5, choices=CAR_TYPES, default='NONE')
    capacity = models.IntegerField(blank=True, null=True)
    special_vehicle_info = models.CharField(max_length=200, blank=True, null=True)

docker-deploy/web-app/templates/base.html
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}RideSharing{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

docker-deploy/web-app/templates/driver_reg.html
{% extends "base.html" %}

{% block title %}Become a Driver{% endblock %}

{% block content %}
<h2>Become a Driver</h2>
<form method='post'>
  {% csrf_token %}
  {{ u_form.as_p }}
  {{ v_form.as_p }}
  <button type='submit'>Submit</button>
</form>
{% endblock %}

docker-deploy/web-app/templates/edit_profile.html
{% extends "base.html" %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
<h2>Edit Profile</h2>
<form method='post'>
  {% csrf_token %}
  {{ b_form.as_p }}
  {{ d_form.as_p }}
  <button type='submit'>Submit</button>
</form>
{% endblock %}

docker-deploy/web-app/templates/edit_request.html
{% extends "base.html" %}

{% block title %}Edit ride request{% endblock %}

{% block content %}
<h2>Your ride request</h2>
<form method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button type='submit'>Submit</button>
</form>
{% endblock %}

docker-deploy/web-app/templates/edit_vehicle.html
{% extends "base.html" %}

{% block title %}Edit vehicle info{% endblock %}

{% block content %}
<h2>Your vehicle</h2>
<form method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button type='submit'>Submit</button>
</form>
<form action="{% url 'quit-driver' %}" method="post">
  {% csrf_token %}
  Don't want to be a driver?
  <input type="submit" value="Quit">
</form>
{% endblock %}

docker-deploy/web-app/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'account-prof' %}">View Profile</a></p>
  <p><a href="{% url 'make-ride-request' %}">Request a ride</a></p>
  <p>
    {% if user.is_driver %}
      <a href="{% url 'open-rides-drive' %}">Become the driver of a ride!</a></p>
    {% endif %}
  </p>
  <p><a href="{% url 'open-rides-share' %}">Search for a sharing ride</a></p>
  <p><a href="{% url 'show-my-rides' 'all' %}">Rides in progress</a></p>
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a> |
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
{% endblock %}

docker-deploy/web-app/templates/my_prof.html
{% extends "base.html" %}

{% block title %}My profile{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user }}!
  <div>
    <p>Username: {{user.username}}</p>
    <p>First name: {{user.first_name}}</p>
    <p>Last name: {{user.last_name}}</p>
    <p>Email: {{user.email}}</p>
    <p>Phone number: {{user.phone_number}}</p>
    <p>
      Driver: 
      {% if user.is_driver %}
        Yes
      {% else %}
        No
      {% endif %}
    </p>
  </div>
  <div>
    {% if user.is_driver %}
        <p>Congratulations! You are a driver!</p>
        <p>Plate number: {{user.vehicle.plate_num}}</p>
        <p>Vehicle type: {{user.vehicle.get_type_display}}</p>
        <p>Vehicle capacity: {{user.vehicle.capacity}}</p>
        <p>Special vehicle info: {{user.vehicle.special_vehicle_info}}</p>
        {% if can_edit %}
          <p><a href="{% url 'edit-vehicle-info' %}">Edit vehicle info</a></p>
        {% else %}
          You can edit your vehicle info after all the driving rides are completed! See 
          <a href="{% url 'show-my-rides' 'driver' %}">Rides in progress</a>
        {% endif %}
    {% else %}
        <p><a href="{% url 'driver-register' %}">Become a driver now!</a></p>
    {% endif %}
    <p><a href="{% url 'edit-profile' %}">Edit Profile</a></p>
    <p><a href="{% url 'passwd-change' %}">Change Password</a></p>
    <p><a href="{% url 'home' %}">Home</a></p>
    <p><a href="{% url 'logout' %}">Log Out</a></p>
  </div>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a> |
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
{% endblock %}

docker-deploy/web-app/templates/my_rides.html
{% extends "base.html" %}

{% block title %}My rides{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <h2>Here are your rides!</h2>
  <a href="{% url 'show-my-rides' 'all' %}">All my rides | </a>
  <a href="{% url 'show-my-rides' 'owner' %}">Rides I requested | </a>
  <a href="{% url 'show-my-rides' 'sharer' %}">Rides-As a sharer | </a>
  {% if user.is_driver %}
    <a href="{% url 'show-my-rides' 'driver' %}">Rides-As a driver</a>
  {% endif %}
  {% for ride in rides %}
    <div>
        <p>Destination: {{ ride.destination }}  |  Arrival time: {{ ride.arrival_time}}</p>
        <p>
            Your role: 
            {% if ride.owner == user %}
                Owner 
            {% elif ride.driver == user %}
                Driver 
            {% else %}
                Sharer 
            {% endif %}
        </p>
        <a href="{% url 'view-ride' ride.pk 'owner' 0 'show-my-rides' %}">View the ride</a> 
    </div>
    <p>---------------------------------------------------------------</p>
  {% endfor %}
  <p><a href="{% url 'home' %}">Home</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a> 
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
{% endblock %}

docker-deploy/web-app/templates/open_rides.html
{% extends "base.html" %}

{% block title %}Open rides{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  {% if mode == 'share' and form %}
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
  <h2>
    {% if not form %}
      Here are rides you can choose to 
      {% if mode == 'share' %}
        Share!
      {% elif mode == 'drive' %}
        Drive!
      {% endif %}
    {% endif %}
  </h2>
  {% for ride in rides %}
    <div>
      <p>Destination: {{ ride.destination }}  |  Arrival time: {{ ride.arrival_time}}</p>
      
      <a href="{% url 'view-ride' ride.pk mode share_ride_id back_url %}">View the detail</a> 
    </div>
    <p>---------------------------------------------------------------</p>
  {% endfor %}
  {% if not form and mode == 'share' %}
    <p><a href="{% url 'open-rides-share' %}">Back to search</a></p>
  {% endif %}
  <p><a href="{% url 'home' %}">Home</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a> 
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
{% endblock %}

docker-deploy/web-app/templates/passwd_change.html
{% extends "base.html" %}

{% block title %}Change the Password{% endblock %}

{% block content %}

<h2>Change the Password</h2>
<form method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button type='submit'>Submit</button>
</form>
{% endblock %}

docker-deploy/web-app/templates/ride_detail.html
{% extends "base.html" %}

{% block title %}Ride detail{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <h2>Ride details</h2>
  <div>
    <ul>
      <li>Destination: {{ ride.destination }}</li>
      <li>Arrival time: {{ ride.arrival_time }}</li>
      <li>Number of passengers: {{ ride.number_of_passengers_sum }}</li>
      <li>Shared: 
        {% if ride.shared %}
          Yes
        {% else %}
          No
        {% endif %}
      </li>
      <li>Stauts: {{ ride.get_status_display }}</li>
      <li>Special request: {{ ride.special_request }}</li>
    </ul>
      {% if role == 'Owner' %}
        {% if ride.status == 'OPEN' %}
          <a href="{% url 'edit-ride' ride.pk %}">Edit the ride</a> 
        {% else %}
          <p>You cannot edit the ride after it is confired by the driver!</p>
        {% endif %}
      {% elif role == 'Driver' %}
        {% if ride.status == 'CONFIRMED' %}
          <form action="{% url 'complete-ride' ride.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Complete the ride">
          </form>
        {% endif %}
      {% elif role == 'Sharer' %}
        {% if ride.status == 'OPEN' %}
          <form action="{% url 'quit-ride' ride.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Quit the ride">
          </form>
        {% endif %}
      {% else %}
        {% if mode == 'share' %}
          <form action="{% url 'share-ride' ride.pk share_ride_id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Join the ride">
          </form>
        {% endif %}
        {% if mode == 'drive' %}
          <form action="{% url 'drive-ride' ride.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Start the ride">
          </form>
        {% endif %}
      {% endif %}
  </div>
  <div>
    {% if ride.status != 'OPEN' %}
      <h4>Driver info:</h4>
      <p>First name: {{ ride.driver.first_name }}</p>
      <p>Last name: {{ ride.driver.last_name }}</p>
      <h4>Vehicle info: </h4>
      <p>Plate number: {{ ride.driver.vehicle.plate_num }}</p>
      <p>Vehicle type: {{ ride.driver.vehicle.get_type_display }}</p>
      <p>Capacity: {{ ride.driver.vehicle.capacity }}</p>
      <p>Special vehicle info: {{ ride.driver.vehicle.special_vehicle_info }}</p>
    {% endif %}
  </div>
  <div>
    <h4>Passenger info:</h4>
    <h5>Owner info:</h5>
    <div>
      <p>First name: {{ owner.first_name }}</p>
      <p>Last name: {{ owner.last_name }}</p>
      <p>Number of passengers: {{ ride.number_of_passengers }}</p>
    </div>
    <% if sharer_rides %>
      <h5>Sharer info:</h5>
      {% for sharer_ride in sharer_rides %}
        <p>First name: {{ sharer_ride.owner.first_name }}</p>
        <p>Last name: {{ sharer_ride.owner.last_name }}</p>
        <p>Number of passengers: {{ sharer_ride.number_of_passengers }}</p>
        <p>---------------------------------------------------------------</p>
      {% endfor %}
    {% endif %}
  </div>
  </div>
  {% if back_url == 'show-my-rides' %}
    <a href="{% url back_url 'all' %}">Back to list</a> 
  {% else %}
    <a href="{% url back_url %}">Back</a>
  {% endif %}
  
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a> 
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
{% endblock %}

docker-deploy/web-app/templates/ride_request.html
{% extends "base.html" %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% block title %}Request a ride{% endblock %}

{% block content %}
<h2>Go for a ride now!</h2>
<form method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button type='submit'>Submit</button>
</form>
{% endblock %}